spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb?DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
      path: /console/
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: 'false'
  hibernate:
    ddl-auto: validate
  server:
    error:
      include-message: always